version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - D:/DockerStorage:/var/lib/postgresql/data

volumes:
  my_db_data:
